repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
        types:
          - python
      - id: ruff-format
        types:
          - python

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-ll"]
        files: .py$

  - repo: local
    hooks:
      - id: pre-commit-branch-validation
        name: Branch Name Validation (local)
        entry: pre-commit-branch-validation
        language: python
        stages: [post-commit, post-checkout]
